# This file was automatically generated by SWIG
package p5namot;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package p5namot;
bootstrap p5namot;
package p5namot;
@EXPORT = qw( );
1;
